### ISSUE TITLE
ImportError: Error loading shared library libffi.so.6

### ISSUE THREAD

**Issue by PatMyron** [cclauss/Find-Python-syntax-errors-action#1]
https://github.com/PatMyron/advent-of-code/runs/75760461

**Comment by PatMyron** [comment]
I think this was https://github.com/jfloff/alpine-python/issues/48. Seems to be passing this step now on other repositories: https://github.com/tensorpack/tensorpack/runs/147903219

**Comment by cclauss** [comment]
@PatMyron Thanks!  Can I ask you to rerun the tests now that I have added more flake8 tests.  Your feedback is helpful.

**Comment by PatMyron** [comment]
@cclauss is this action a subset of flake8? https://github.com/cclauss/GitHub-Action-for-Flake8 passes on my repos

**Comment by cclauss** [comment]
Yes ...  The __--select__ statement is picking a subset of all flake8 codes.  If you want them all, you can try https://github.com/cclauss/GitHub-Action-for-Flake8.  Thanks for your feedback.
