### ISSUE TITLE
Question: excluding a directory 

### ISSUE THREAD

**Issue by danyaljj** [cclauss/Find-Python-syntax-errors-action#3]
Is there a way to exclude a directory?

**Comment by cclauss** [comment]
For more tests and more control you can [do this](https://github.com/cclauss/Find-Python-syntax-errors-action/blob/master/README.md#for-more-tests-and-more-control-instead-of-using-this-action) and then add a [`flake8 --exclude=bad/directory`](https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-exclude) option to the first flake8 test.

**Comment by danyaljj** [comment]
Thanks!
