### ISSUE TITLE
Python 3.8+ syntax

### ISSUE THREAD

**Issue by augustomen** [cclauss/Find-Python-syntax-errors-action#4]
The [Dockerfile](https://github.com/cclauss/Find-Python-syntax-errors-action/blob/07e62fece7a75d3e3a870dea1f0b1760767975a1/Dockerfile) extends `python:3.7`. This means it will reject Python 3.8+ syntax changes like the Walrus operator:

    while myvar := myfunc():

Forgive the ignorance, but is there an option in the Github workflow file to change the version of Python? And if not, is there a plan to support it?

**Comment by cclauss** [comment]
Updated to use current Python ...

Also see https://github.com/cclauss/Find-Python-syntax-errors-action#for-more-tests-and-more-control-instead-of-using-this-action
